### ISSUE TITLE
Video Only results on AudioSet-20K

### ISSUE THREAD

**Issue by GenjiB** [YuanGongND/uavm#2]
Hi, 

I can reproduce the results of finetuning on Audioset 20K with the multimodal setting. 
However, I tried to get the visual-only baseline from the multimodal pre-trained weights. I can only get 13.11 (missingvideoonly setting) and 12.7 (videoonly). 

Pretrained ViT-B-16  on ImageNet-21K with multimodal script can get ~9.5mAP. 
Pretrained CAV-MAE  with audioonly script can get ~17.6 mAP. 

Do you have the script for training videoonly baseline?

Thank you

**Comment by YuanGongND** [comment]
Hi there,

Did you mean UAVM (this repo) or CAV-MAE? Thanks!

-Yuan

**Comment by GenjiB** [comment]
oh. It should be CAV-MAE. Sorry~

Let me move it to the correct repo.
