### ISSUE TITLE
How to prepare datasets for UVAM

### ISSUE THREAD

**Issue by rizentan** [YuanGongND/uavm#5]
Sorry to bother you, I would like to download the dataset from the VGG Sound official website, but it no longer provides download services. Do you have any good suggestions? I want to use my own dataset to train UAVM, but I don't know what format and organized to set for the dataset.

**Comment by YuanGongND** [comment]
hi there,

These are two different questions:

> I would like to download the dataset from the VGG Sound official website, but it no longer provides download services.

See the readme file:

> VGGSound Pretrained Audio and Video Features
> 
> [Audio Features](https://www.dropbox.com/s/px08p7zgovh7b3p/a_feat.zip?dl=1) (~20GB)
> 
> [Video Features](https://www.dropbox.com/s/qv1umuxg1rq4dzg/v_feat.zip?dl=1) (~10GB)

We do provide processed VGGSound data, you can use these to train the model. We cannot release raw data, but the extracted feature should be good enough. Meanwhile, the feature extractors are also released. 

> I want to use my own dataset to train UAVM, but I don't know what format and organized to set for the dataset.

I recommend to run the "1-click" recipe (in the readme file, there is a detailed instruction). And check the intermediate files, so you know how to organize the training data.

Having said that, this model is a very special model that can take both audio and video data, but **one thing at a time**. Please make sure it fits your application, most audio-visual model aims to take audio and video data jointly.

-Yuan

**Comment by rizentan** [comment]
Thank you very much for your reply.

**Comment by rizentan** [comment]
Thank you very much for your reply.

**Comment by rizentan** [comment]
Thank you very much for your reply.
